[package]
name = "htmlrs"
version = "0.1.2"
edition = "2021"
license = "MIT"
description = "htmlrs"
homepage = "https://github.com/MNThomson/htmlrs"

[dependencies]
leptos = { version = "0.6", features = ["ssr", "experimental-islands"] }
